### ISSUE TITLE
Issue with running multi-fidelity BO notebook.

### ISSUE THREAD

**Issue by PC-FSU** [EmuKit/emukit#387]
System and package information 

OS : Windows 10, verision 1909, build : 18363.1440
Python : Python 3.7.10, (MSC v.1916 64 bit (AMD64))
Scipy : 1.7.0
Numpy : '1.21.1'
Setuptools : '52.0.0.post20210125'
GPy :  '1.10.0'
emcee : 3.1.0

I have a version of "Emukit-tutorial-multi-fidelity-bayesian-optimization.ipynb" adapted in two different .py scripts, and I am trying to replicate the result of the Forrester example.  File emukit_wrapper.py contains the functionality for Initializing the model, defining the acquisition function, and running the bayesian optimization loop.  

        `import numpy as np
        np.random.seed(12345)
        from emukit.multi_fidelity.convert_lists_to_array import convert_x_list_to_array
        from emukit.core import ParameterSpace, ContinuousParameter, InformationSourceParameter
        from emukit.multi_fidelity.models.linear_model import GPyLinearMultiFidelityModel
        import GPy
        from emukit.multi_fidelity.kernels.linear_multi_fidelity_kernel import LinearMultiFidelityKernel
        from emukit.multi_fidelity.convert_lists_to_array import convert_xy_lists_to_arrays
        from emukit.model_wrappers import GPyMultiOutputWrapper
        from GPy.models.gp_regression import GPRegression
        from emukit.bayesian_optimization.acquisitions.entropy_search import MultiInformationSourceEntropySearch
        from emukit.core.acquisition import Acquisition
        from emukit.core.loop import FixedIntervalUpdater, OuterLoop, SequentialPointCalculator
        from emukit.core.loop.loop_state import create_loop_state
        from emukit.core.optimization.multi_source_acquisition_optimizer import MultiSourceAcquisitionOptimizer
        from emukit.core.optimization import GradientAcquisitionOptimizer
        from emukit.core.loop.user_function import MultiSourceFunctionWrapper
        from scipy.optimize import minimize
        from emukit.bayesian_optimization.loops import BayesianOptimizationLoop
        from emukit.bayesian_optimization.acquisitions.entropy_search import EntropySearch
        from emukit.model_wrappers import GPyModelWrapper
        import GPy
        
        class EmukitMultifidelity():
        
            def __init__(self, fidelities, n_fidelities, costs,
                         n_optimization_restarts=5, verbose_optimization=False):
        
                assert len(fidelities) == n_fidelities, "number of fidelity functions should be same as n_fidelities"
                # for fid in fidelities: assert type(fid) is function
        
                self.fidelities = fidelities
                self.n_fidelities = n_fidelities
                self.cost_list = costs
                self.x_array = None
                self.y_array = None
                self.model = None
                self.acquisition = None
                self.loop = None
                self.input_dimensions = None
                self.n_optimization_restarts = n_optimization_restarts
                self.verbose_optimization = verbose_optimization
        
                print('Warning! the following limitations/assumptions hold: \n'
                      '1. assumes discrete set of fidelities \n'
                      '2. assumes an RBF kernel for all fidelities \n'
                      '3. all RBF kernels assume a lengthscale bounded by [0.01, 0.5] \n'
                      '4. input space is assumed to be in [0,1]^d. Be sure to normalize inputs \n'
                      '5. the input parameter space is assumed to be 1d. Change param_space() to modify this \n'
                      )
                return
        
            def fidelity_func_wrapper(self):
                user_function = MultiSourceFunctionWrapper([
                    lambda x: self.fidelities[i](x) for i in range(self.n_fidelities)
                ])
                return user_function
        
            def param_space(self):
                # HARD CODE alert: need to change for >1 dimensions
                return ParameterSpace([ContinuousParameter('x', 0, 1),
                                       InformationSourceParameter(self.n_fidelities)])
        
            def initialize(self, x_list, y_list):
                assert len(x_list) == self.n_fidelities, "you should provide initial data for each fidelity"
                assert len(y_list) == self.n_fidelities, "you should provide initial data for each fidelity"
                self.x_array, self.y_array = convert_xy_lists_to_arrays(x_list, y_list)
                return
        
            def mfmodel(self):
                input_dimensions = self.x_array.shape[-1]-1
        
                kernels = []
                for i in range(self.n_fidelities):
                    kernel = GPy.kern.RBF(input_dimensions)
                    kernel.lengthscale.constrain_bounded(0.01, 0.5) # create
                    kernels.append(kernel)
        
                multi_fidelity_kernel = LinearMultiFidelityKernel(kernels)
                gpy_model = GPyLinearMultiFidelityModel(self.x_array, self.y_array, multi_fidelity_kernel, self.n_fidelities)
        
                # needs to be modified for > 2 fidelities
                gpy_model.likelihood.Gaussian_noise.fix(0.1)
                gpy_model.likelihood.Gaussian_noise_1.fix(0.1)
        
                self.model = GPyMultiOutputWrapper(gpy_model, n_outputs=self.n_fidelities,
                                                   n_optimization_restarts=self.n_optimization_restarts,
                                                   verbose_optimization=self.verbose_optimization)
                self.model.optimize()
                self.input_dimensions = input_dimensions
        
                return
        
            def multifidelity_acquisition_function(self):
                # Define cost of different fidelities as acquisition function
                class Cost(Acquisition):
                    def __init__(Cself, costs):
                        Cself.costs = costs
        
                    def evaluate(Cself, x):
                        fidelity_index = x[:, -1].astype(int)
                        x_cost = np.array([Cself.costs[i] for i in fidelity_index])
                        return x_cost[:, None]
        
                    @property
                    def has_gradients(Cself):
                        return True
        
                    def evaluate_with_gradients(Cself, x):
                        return Cself.evalute(x), np.zeros(x.shape)
        
                cost_acquisition = Cost(self.cost_list)
                self.cost_acquisition = cost_acquisition
                self.acquisition = MultiInformationSourceEntropySearch(self.model, self.param_space()) / self.cost_acquisition
                return
        
            def mfbo_loop(self, num_iters):
                initial_loop_state = create_loop_state(self.x_array, self.y_array)
                acquisition_optimizer = MultiSourceAcquisitionOptimizer(GradientAcquisitionOptimizer(self.param_space()),
                                                                        self.param_space())
                candidate_point_calculator = SequentialPointCalculator(self.acquisition, acquisition_optimizer)
                model_updater = FixedIntervalUpdater(self.model)
                self.loop = OuterLoop(candidate_point_calculator, model_updater, initial_loop_state)
                self.pmean_minimizer = []
                self.pmean_minimum = []
                self.cost = []
                def optimize_posterior_mean_event(loop, loop_state):
                    pmean_minimizer = self.optimize_posterior_mean(opt='minimize')
                    self.pmean_minimizer.append((pmean_minimizer))
                self.loop.iteration_end_event.append(optimize_posterior_mean_event)
                self.loop.run_loop(self.fidelity_func_wrapper(), num_iters)
        
                return
        
            def gp_model_hf(self, x, fidelity=1.0):
                # self.mfmodel()
                # Expose the GP posterior mean and variance
                assert x.shape[-1] == self.input_dimensions, "x should not include fidelity parameter"
                x = np.array(x).reshape(-1, self.input_dimensions)
                fid = np.ones(x.shape[0]).reshape(-1,1) * fidelity
                x_aug = np.hstack((x, fid))
                return self.loop.model_updaters[0].model.predict(x_aug)
        
            def optimize_posterior_mean(self, opt='minimize'):
                # max/min the posterior mean at any fidelity. Usually we are interested in highest fidelity
                if opt.lower() == 'minimize':
                    print('minimizing posterior mean at highest fidelity')
                    obj = lambda x: self.gp_model_hf(x, 1.0)[0] # [0] returns mean, [1] returns var
                elif opt.lower() == 'maximize':
                    print('maximizing posterior mean at highest fidelity')
                    obj = lambda x: -1. * self.gp_model_hf(x, 1.0)[0]
                res = minimize(obj, np.ones(self.input_dimensions) * 0.5, method='Nelder-Mead', tol=1e-6)
                return res.x
`

I am calling `emukit_wrapper.py` from another file called `emukit_forrester_example.py` in which the problem routine for the two-fidelity Forrester function is defined.

          `import sys
          #sys.path.append('../src/')
          import os
          from emukit_wrapper import *
          import emukit.test_functions.forrester # test function
          import numpy as np
          import argparse
          
          parser = argparse.ArgumentParser()
          parser.add_argument('niters', type=int, default=1, help='number of BO iterations')
          parser.add_argument('repetitions', type=int, default=1, help='number of independent BO repetitions')
          args = parser.parse_args()
          niters = args.niters
          repetitions = args.repetitions
          
          # define test function
          forrester_fcn, _ = emukit.test_functions.forrester.multi_fidelity_forrester_function()
          forrester_fcn_low = forrester_fcn.f[0]
          forrester_fcn_high = forrester_fcn.f[1]
          
          
          
          ## Assign costs
          low_fidelity_cost = 1
          high_fidelity_cost = 5
          
          print(niters,repetitions,forrester_fcn.f[0])
          
          fidelities = [forrester_fcn_low, forrester_fcn_high]
          n_fidelities = 2
          costs = [low_fidelity_cost, high_fidelity_cost]
          verbose_optimization = True
          ## create object instance
          mf = EmukitMultifidelity(fidelities, n_fidelities, costs,verbose_optimization)
          
          for rep in range(repetitions):
              
              np.random.seed(rep + 123)
              post_maximizer = []
              final_rec = []
          
              x_low  = np.random.rand(12)[:, None]
              x_high = x_low[:6, :]
              y_low  = forrester_fcn_low(x_low)
              y_high = forrester_fcn_high(x_high)
              x_list = [x_low.astype(float), x_high.astype(float)]
              y_list = [y_low.astype(float), y_high.astype(float)]
              
              print("\n x : \n",x_low,x_high,x_list)
              print("\n y : \n",y_low,y_high,y_list)
              
              mf.initialize(x_list, y_list)
              mf.mfmodel()
              mf.multifidelity_acquisition_function()
              mf.mfbo_loop(niters)
          
          
              # save to file
              X = np.concatenate(mf.loop.loop_state.X).reshape(-1, mf.input_dimensions+1)
              Y = np.concatenate(mf.loop.loop_state.Y)
              muxstar = np.concatenate(mf.pmean_minimizer).reshape(-1, mf.input_dimensions) # posterior mean minimizer\
              costs = mf.cost_acquisition.evaluate(X)
              np.save('rep' + str(rep) + '_' + 'posterior_mean_minimizer.npy', muxstar)
              np.save('rep' + str(rep) + '_' + 'X.npy', X)
              np.save('rep' + str(rep) + '_' + 'Y.npy', Y)
              np.save('rep' + str(rep) + '_' + 'costs.npy', costs)
`
 Running `emukit_forrester_example.py` throws the following error 

        `Traceback (most recent call last):
          File "emukit_forrester_example.py", line 55, in <module>
            mf.mfbo_loop(niters)
          File "C:\Users\18503\emukit\emukit_wrapper.py", line 131, in mfbo_loop
            self.loop.run_loop(self.fidelity_func_wrapper(), num_iters)
          File "C:\Users\18503\AppData\Local\Continuum\anaconda3\envs\dragonfly\lib\site-packages\emukit\core\loop\outer_loop.py", line 92, in run_loop
            new_x = self.candidate_point_calculator.compute_next_points(self.loop_state, context)
          File "C:\Users\18503\AppData\Local\Continuum\anaconda3\envs\dragonfly\lib\site-packages\emukit\core\loop\candidate_point_calculators.py", line 50, in compute_next_points
            x, _ = self.acquisition_optimizer.optimize(self.acquisition, context)
          File "C:\Users\18503\AppData\Local\Continuum\anaconda3\envs\dragonfly\lib\site-packages\emukit\core\optimization\multi_source_acquisition_optimizer.py", line 74, in optimize
            x, f_maxs[i] = self.acquisition_optimizer.optimize(acquisition, context)
          File "C:\Users\18503\AppData\Local\Continuum\anaconda3\envs\dragonfly\lib\site-packages\emukit\core\optimization\acquisition_optimizer.py", line 65, in optimize
            max_x, max_value = self._optimize(acquisition, context_manager)
          File "C:\Users\18503\AppData\Local\Continuum\anaconda3\envs\dragonfly\lib\site-packages\emukit\core\optimization\gradient_acquisition_optimizer.py", line 58, in _optimize
            anchor_points = anchor_points_generator.get(num_anchor=1, context_manager=context_manager)
          File "C:\Users\18503\AppData\Local\Continuum\anaconda3\envs\dragonfly\lib\site-packages\emukit\core\optimization\anchor_points_generator.py", line 62, in get
            scores = self.get_anchor_point_scores(X)
          File "C:\Users\18503\AppData\Local\Continuum\anaconda3\envs\dragonfly\lib\site-packages\emukit\core\optimization\anchor_points_generator.py", line 90, in get_anchor_point_scores
            scores[are_constraints_satisfied] = self.acquisition.evaluate(X[are_constraints_satisfied, :])[:, 0]
          File "C:\Users\18503\AppData\Local\Continuum\anaconda3\envs\dragonfly\lib\site-packages\emukit\core\acquisition\acquisition.py", line 96, in evaluate
            return self.numerator.evaluate(x) / self.denominator.evaluate(x)
          File "C:\Users\18503\AppData\Local\Continuum\anaconda3\envs\dragonfly\lib\site-packages\emukit\bayesian_optimization\acquisitions\entropy_search.py", line 157, in evaluate
            results[j] = self.evaluate(x[j, None, :])
          File "C:\Users\18503\AppData\Local\Continuum\anaconda3\envs\dragonfly\lib\site-packages\emukit\bayesian_optimization\acquisitions\entropy_search.py", line 165, in evaluate
            dMdx, dVdx = self._innovations(x)
          File "C:\Users\18503\AppData\Local\Continuum\anaconda3\envs\dragonfly\lib\site-packages\emukit\bayesian_optimization\acquisitions\entropy_search.py", line 207, in _innovations
            sigma_x_rep = self.model.get_covariance_between_points(self.representer_points, x)
          File "C:\Users\18503\AppData\Local\Continuum\anaconda3\envs\dragonfly\lib\site-packages\emukit\model_wrappers\gpy_model_wrappers.py", line 313, in get_covariance_between_points
            return self.gpy_model.posterior_covariance_between_points(X1, X2)
          File "C:\Users\18503\AppData\Local\Continuum\anaconda3\envs\dragonfly\lib\site-packages\GPy\core\gp.py", line 774, in posterior_covariance_between_points
            Y_metadata=Y_metadata)
          File "C:\Users\18503\AppData\Local\Continuum\anaconda3\envs\dragonfly\lib\site-packages\GPy\likelihoods\mixed_noise.py", line 44, in predictive_values
            ind = Y_metadata['output_index'].flatten()
        TypeError: 'NoneType' object is not subscriptable`

In previous issues, i saw that this can be fixed by setting  `include_likelihood = False` in the function definition of  posterior_covariance_between_points ( in file `~/lib/python3.7/site-packages/GPy/core/gp.py`)

` posterior_covariance_between_points(self, X1, X2, Y_metadata=None, 
                                              likelihood=None, include_likelihood=False)`

After setting  `include_likelihood = False`, I face a compatibility issue with scipy. 

        `  File "emukit_forrester_example.py", line 58, in <module>
            mf.mfbo_loop(niters)
          File "C:\Users\18503\emukit\emukit_wrapper.py", line 131, in mfbo_loop
            self.loop.run_loop(self.fidelity_func_wrapper(), num_iters)
          File "C:\Users\18503\AppData\Local\Continuum\anaconda3\envs\dragonfly\lib\site-packages\emukit\core\loop\outer_loop.py", line 92, in run_loop
            new_x = self.candidate_point_calculator.compute_next_points(self.loop_state, context)
          File "C:\Users\18503\AppData\Local\Continuum\anaconda3\envs\dragonfly\lib\site-packages\emukit\core\loop\candidate_point_calculators.py", line 50, in compute_next_points
            x, _ = self.acquisition_optimizer.optimize(self.acquisition, context)
          File "C:\Users\18503\AppData\Local\Continuum\anaconda3\envs\dragonfly\lib\site-packages\emukit\core\optimization\multi_source_acquisition_optimizer.py", line 74, in optimize
            x, f_maxs[i] = self.acquisition_optimizer.optimize(acquisition, context)
          File "C:\Users\18503\AppData\Local\Continuum\anaconda3\envs\dragonfly\lib\site-packages\emukit\core\optimization\acquisition_optimizer.py", line 65, in optimize
            max_x, max_value = self._optimize(acquisition, context_manager)
          File "C:\Users\18503\AppData\Local\Continuum\anaconda3\envs\dragonfly\lib\site-packages\emukit\core\optimization\gradient_acquisition_optimizer.py", line 64, in _optimize
            context_manager=context_manager)
          File "C:\Users\18503\AppData\Local\Continuum\anaconda3\envs\dragonfly\lib\site-packages\emukit\core\optimization\optimizer.py", line 117, in apply_optimizer
            optimized_x, _ = optimizer.optimize(problem.x0_no_context, f_no_context, df_no_context, f_df_no_context)
          File "C:\Users\18503\AppData\Local\Continuum\anaconda3\envs\dragonfly\lib\site-packages\emukit\core\optimization\optimizer.py", line 62, in optimize
            res = scipy.optimize.fmin_l_bfgs_b(f, x0=x0, bounds=self.bounds, approx_grad=True, maxiter=self.max_iterations)
          File "C:\Users\18503\AppData\Local\Continuum\anaconda3\envs\dragonfly\lib\site-packages\scipy\optimize\lbfgsb.py", line 198, in fmin_l_bfgs_b
            **opts)
          File "C:\Users\18503\AppData\Local\Continuum\anaconda3\envs\dragonfly\lib\site-packages\scipy\optimize\lbfgsb.py", line 308, in _minimize_lbfgsb
            finite_diff_rel_step=finite_diff_rel_step)
          File "C:\Users\18503\AppData\Local\Continuum\anaconda3\envs\dragonfly\lib\site-packages\scipy\optimize\optimize.py", line 262, in _prepare_scalar_function
            finite_diff_rel_step, bounds, epsilon=epsilon)
          File "C:\Users\18503\AppData\Local\Continuum\anaconda3\envs\dragonfly\lib\site-packages\scipy\optimize\_differentiable_functions.py", line 159, in __init__
            self._update_grad()
          File "C:\Users\18503\AppData\Local\Continuum\anaconda3\envs\dragonfly\lib\site-packages\scipy\optimize\_differentiable_functions.py", line 238, in _update_grad
            self._update_grad_impl()
          File "C:\Users\18503\AppData\Local\Continuum\anaconda3\envs\dragonfly\lib\site-packages\scipy\optimize\_differentiable_functions.py", line 156, in update_grad
            **finite_diff_options)
          File "C:\Users\18503\AppData\Local\Continuum\anaconda3\envs\dragonfly\lib\site-packages\scipy\optimize\_numdiff.py", line 448, in approx_derivative
            raise ValueError("`f0` passed has more than 1 dimension.")
        ValueError: `f0` passed has more than 1 dimension.`
 
Any suggestion on how could I fix that.

**Comment by PC-FSU** [comment]
Also checked on another HPC system, and face the same issue. Following are the configuration of the os:
OS : Linux 3.10.0-1127.18.2.el7.x86_64 x86_64
Python : Python 3.7.3 , [GCC 7.3.0]
Scipy : 1.7.1
Numpy : '1.21.1'
Setuptools : '52.0.0.post20210125'
GPy : '1.10.0'
      `importing GPy throws the following warning : 
      warning in stationary: failed to import cython module: falling back to numpy
      warning in coregionalize: failed to import cython module: falling back to numpy
      warning in choleskies: failed to import cython module: falling back to numpy`
emcee : 3.1.0

**Comment by apaleyes** [comment]
Thanks for the report. Managed to reproduce the latter error, will look into a fix

**Comment by apaleyes** [comment]
The fix is merged, and shall become the part of the next (hopefully soon to come) release. Thanks for reporting!
